name: d4-vton
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pip=20.3.3
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.5
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchvision=0.12.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.9.0
    - aiosignal==1.3.1
    - albumentations==0.4.3
    - altair==5.1.2
    - antlr4-python3-runtime==4.8
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.3
    - bezier==2023.7.28
    - bleach==6.1.0
    - blessed==1.20.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - click==8.1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diffusers==0.23.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - einops==0.3.0
    - executing==2.0.1
    - fairscale==0.4.13
    - fastjsonschema==2.20.0
    - filelock==3.13.1
    - fonttools==4.45.0
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - ftfy==6.1.3
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.23.4
    - google-auth-oauthlib==1.0.0
    - grpcio==1.59.3
    - huggingface-hub==0.19.4
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imgaug==0.2.6
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - invisible-watermark==0.2.0
    - ipython==8.12.3
    - jedi==0.19.1
    - jinja2==3.1.2
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.1
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.5
    - kornia==0.6.0
    - lazy-loader==0.3
    - lightning-utilities==0.10.0
    - markdown==3.5.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.4
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.0.2
    - multidict==6.0.4
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-ml-py==12.535.133
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - openai-clip==1.0.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.8.1.78
    - packaging==23.2
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pipreqs==0.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - prompt-toolkit==3.0.47
    - protobuf==4.25.1
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pudb==2019.2
    - pure-eval==0.2.3
    - pyarrow==14.0.1
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.7
    - pydeck==0.8.1b0
    - pydeprecate==0.3.1
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.4.2
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==26.0.3
    - referencing==0.31.0
    - regex==2023.10.3
    - requests-oauthlib==1.3.1
    - rich==13.7.0
    - rpds-py==0.13.1
    - rsa==4.9
    - safetensors==0.4.0
    - scikit-image==0.19.3
    - scipy==1.10.1
    - sentry-sdk==2.12.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - streamlit==1.28.2
    - tenacity==8.2.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - test-tube==0.7.5
    - tifffile==2023.7.10
    - tinycss2==1.3.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - toolz==0.12.0
    - torchmetrics==0.6.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.14.3
    - transformers==4.19.2
    - tzdata==2023.3
    - tzlocal==5.2
    - urwid==2.2.3
    - validators==0.22.0
    - wandb==0.17.5
    - watchdog==3.0.0
    - wcwidth==0.2.12
    - webencodings==0.5.1
    - werkzeug==3.0.1
    - yarg==0.1.9
    - yarl==1.9.3
    - zipp==3.17.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip